services:
  - type: web
    name: taskbuddy-backend
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/taskbuddy_backend_monolithic_jwt-0.0.1.jar
    envVars:
      - key: DATABASE_URL
        value: jdbc:mysql://switchyard.proxy.rlwy.net:14218/railway
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: gDuTUzYPFQIXYGxRSwmuzHwrwvoHskfj
      - key: JWT_SECRET
        value: rG6N4lZpXhZ8nR5+6mXq0n7b5E5x6Kp9K0RZc9M2Wq4=
      - key: RAZORPAY_KEY_ID
        value: rzp_test_SCncJ3HITMHt1w
      - key: RAZORPAY_KEY_SECRET
        value: NaU5DaGYDr9LxVruK1ygR01q
